---
title: "git_00"
author: "Ashley Davis"
date: "Year 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
He thought he saw an Elephant  
That practised on a fife:  
He looked again, and found it was  
A letter from his wife.  
"At length I realise," he said,  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  
      
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
In tender moments of birth's embrace,  
Postpartum doulas lend their grace.  
A beacon of support when night turns long,  
They nurture mothers, both fierce and strong.  

With gentle hands and hearts so kind,  
They bring solace to weary minds.  
Guiding through the haze of sleepless nights,  
They offer comfort, turning darkness into light.  

With wisdom shared from experience deep,  
Postpartum doulas gently weep,  
Witnessing the joys and struggles faced,  
Helping new families find their place.  

They ease the doubts and calm the fears,  
Wiping away unshed tears.  
Their presence a balm in the weary storm,  
Postpartum doulas, a loving form.  

Through gentle touch and words of care,  
They create a haven, a sanctuary rare.  
Lending strength when exhaustion seeps,  
Postpartum doulas cradle love's keep.  

For in the tender days after birth,  
They bring warmth to the hearth,  
Embracing families with love's sweet hue,  
Postpartum doulas, forever true.  